import PROJECT_ROLES from './projectRoles.js';
import PROJECT_PERMISSIONS from './projectPermission.js';

export const PROJECT_ROLE_PERMISSIONS = Object.freeze({
  [PROJECT_ROLES.OWNER]: [
    // Project
    PROJECT_PERMISSIONS.VIEW_PROJECT,
    PROJECT_PERMISSIONS.UPDATE_PROJECT,
    PROJECT_PERMISSIONS.ARCHIVE_PROJECT,
    PROJECT_PERMISSIONS.RESTORE_PROJECT,

    // Tasks
    PROJECT_PERMISSIONS.CREATE_TASK,
    PROJECT_PERMISSIONS.UPDATE_TASK,
    PROJECT_PERMISSIONS.DELETE_TASK,
    PROJECT_PERMISSIONS.ARCHIVE_TASK,
    PROJECT_PERMISSIONS.RESTORE_TASK,
    PROJECT_PERMISSIONS.ASSIGN_TASK,

    // Subtasks
    PROJECT_PERMISSIONS.CREATE_SUBTASK,
    PROJECT_PERMISSIONS.UPDATE_SUBTASK,
    PROJECT_PERMISSIONS.DELETE_SUBTASK,

    // Members
    PROJECT_PERMISSIONS.VIEW_PROJECT_MEMBERS,
    PROJECT_PERMISSIONS.ADD_PROJECT_MEMBER,
    PROJECT_PERMISSIONS.REMOVE_PROJECT_MEMBER,
    PROJECT_PERMISSIONS.CHANGE_PROJECT_ROLE,

    // Comments
    PROJECT_PERMISSIONS.CREATE_COMMENT,
    PROJECT_PERMISSIONS.UPDATE_COMMENT,
    PROJECT_PERMISSIONS.DELETE_COMMENT,
    PROJECT_PERMISSIONS.MODERATE_COMMENT,

    // Labels
    PROJECT_PERMISSIONS.CREATE_LABEL,
    PROJECT_PERMISSIONS.UPDATE_LABEL,
    PROJECT_PERMISSIONS.DELETE_LABEL,
    PROJECT_PERMISSIONS.ASSIGN_LABEL,

    // Attachments
    PROJECT_PERMISSIONS.CREATE_ATTACHMENT,
    PROJECT_PERMISSIONS.DELETE_ATTACHMENT,
    PROJECT_PERMISSIONS.MODERATE_ATTACHMENT,
  ],

  [PROJECT_ROLES.ADMIN]: [
    PROJECT_PERMISSIONS.VIEW_PROJECT,
    PROJECT_PERMISSIONS.UPDATE_PROJECT,
    PROJECT_PERMISSIONS.ARCHIVE_PROJECT,
    PROJECT_PERMISSIONS.RESTORE_PROJECT,

    PROJECT_PERMISSIONS.CREATE_TASK,
    PROJECT_PERMISSIONS.UPDATE_TASK,
    PROJECT_PERMISSIONS.DELETE_TASK,
    PROJECT_PERMISSIONS.ARCHIVE_TASK,
    PROJECT_PERMISSIONS.RESTORE_TASK,
    PROJECT_PERMISSIONS.ASSIGN_TASK,

    PROJECT_PERMISSIONS.CREATE_SUBTASK,
    PROJECT_PERMISSIONS.UPDATE_SUBTASK,
    PROJECT_PERMISSIONS.DELETE_SUBTASK,

    PROJECT_PERMISSIONS.VIEW_PROJECT_MEMBERS,
    PROJECT_PERMISSIONS.ADD_PROJECT_MEMBER,
    PROJECT_PERMISSIONS.REMOVE_PROJECT_MEMBER,
    PROJECT_PERMISSIONS.CHANGE_PROJECT_ROLE,

    PROJECT_PERMISSIONS.CREATE_COMMENT,
    PROJECT_PERMISSIONS.UPDATE_COMMENT,
    PROJECT_PERMISSIONS.DELETE_COMMENT,
    PROJECT_PERMISSIONS.MODERATE_COMMENT,

    PROJECT_PERMISSIONS.CREATE_LABEL,
    PROJECT_PERMISSIONS.UPDATE_LABEL,
    PROJECT_PERMISSIONS.DELETE_LABEL,
    PROJECT_PERMISSIONS.ASSIGN_LABEL,

    // Attachments
    PROJECT_PERMISSIONS.CREATE_ATTACHMENT,
    PROJECT_PERMISSIONS.DELETE_ATTACHMENT,
    PROJECT_PERMISSIONS.MODERATE_ATTACHMENT,
  ],

  [PROJECT_ROLES.MEMBER]: [
    PROJECT_PERMISSIONS.VIEW_PROJECT,

    PROJECT_PERMISSIONS.CREATE_TASK,
    PROJECT_PERMISSIONS.UPDATE_TASK,
    PROJECT_PERMISSIONS.ASSIGN_TASK,

    PROJECT_PERMISSIONS.CREATE_SUBTASK,
    PROJECT_PERMISSIONS.UPDATE_SUBTASK,
    PROJECT_PERMISSIONS.DELETE_SUBTASK,

    PROJECT_PERMISSIONS.VIEW_PROJECT_MEMBERS,

    PROJECT_PERMISSIONS.CREATE_COMMENT,
    PROJECT_PERMISSIONS.UPDATE_COMMENT,
    PROJECT_PERMISSIONS.DELETE_COMMENT,

    PROJECT_PERMISSIONS.ASSIGN_LABEL,

    // Attachments (members may upload, and delete their own uploads)
    PROJECT_PERMISSIONS.CREATE_ATTACHMENT,
    PROJECT_PERMISSIONS.DELETE_ATTACHMENT,
  ],

  [PROJECT_ROLES.VIEWER]: [
    PROJECT_PERMISSIONS.VIEW_PROJECT,
    PROJECT_PERMISSIONS.VIEW_PROJECT_MEMBERS,
  ],
});

export const hasProjectPermission = (role, permission) => {
  return PROJECT_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
};

export default PROJECT_ROLE_PERMISSIONS;
